using System.Globalization;
using System.IO;
using System.Text.Json;

namespace SpatialScope.Windows.Services;

public enum InterfaceLanguage
{
    System,
    English,
    SimplifiedChinese,
}

public sealed class LocalizationService
{
    private static readonly IReadOnlyDictionary<string, string> Chinese = new Dictionary<string, string>
    {
        ["Tagline"] = "空间图像分析",
        ["WorkflowProgress"] = "工作流程进度",
        ["Language"] = "语言",
        ["FollowSystem"] = "跟随系统",
        ["English"] = "English",
        ["SimplifiedChinese"] = "简体中文",
        ["Dataset"] = "数据集",
        ["Channels"] = "个通道",
        ["Scale"] = "比例",
        ["NotSet"] = "未设置",
        ["Compute"] = "计算",
        ["AppCpu"] = "应用 CPU",
        ["Cpus"] = "个 CPU",
        ["Gpus"] = "个 GPU",
        ["GpuAuto"] = "GPU 自动",
        ["CpuAnalysis"] = "CPU 分析",
        ["Step"] = "步骤",
        ["Of"] = "/",
        ["Ready"] = "就绪",
        ["Running"] = "运行中",
        ["Complete"] = "完成",
        ["NeedsAttention"] = "需要处理",
        ["NotStarted"] = "尚未运行",
        ["Choose"] = "选择",
        ["ChooseFolder"] = "选择文件夹",
        ["ChooseColor"] = "选择颜色",
        ["PlotZoomHelp"] = "按住 Ctrl 并滚动鼠标滚轮缩放；放大后拖动平移；双击或按 0 恢复完整视图。",
        ["OpenOutput"] = "打开输出文件夹",
        ["VersionFormat"] = "\u7248\u672c {0}",
        ["CheckForUpdates"] = "\u68c0\u67e5\u66f4\u65b0",
        ["InstallUpdateVersion"] = "\u5b89\u88c5\u66f4\u65b0 {0}",
        ["CheckingForUpdates"] = "\u6b63\u5728\u68c0\u67e5\u66f4\u65b0\u2026",
        ["ApplicationUpToDate"] = "SpatialScope \u5df2\u662f\u6700\u65b0\u7248\u672c\u3002",
        ["ApplicationUpToDateTitle"] = "SpatialScope \u5df2\u662f\u6700\u65b0\u7248\u672c",
        ["ApplicationUpToDateMessage"] = "\u60a8\u6b63\u5728\u4f7f\u7528\u6700\u65b0\u7684 Windows \u7248\u672c\uff08{0}\uff09\u3002",
        ["UpdateAvailableTitle"] = "SpatialScope \u66f4\u65b0\u53ef\u7528",
        ["UpdateAvailableMessage"] = "SpatialScope {0} \u5df2\u53d1\u5e03\u3002\u662f\u5426\u7acb\u5373\u4e0b\u8f7d\u3001\u9a8c\u8bc1\u5e76\u5b89\u88c5\uff1f\n\n\u4e0b\u8f7d\u5b8c\u6210\u540e\uff0cSpatialScope \u5c06\u5173\u95ed\u3001\u5b89\u88c5\u66f4\u65b0\u5e76\u81ea\u52a8\u91cd\u65b0\u6253\u5f00\u3002",
        ["UpdateAvailableStatus"] = "SpatialScope {0} \u53ef\u7528\u3002",
        ["UpdateManualInstallRequiredTitle"] = "\u9700\u8981\u624b\u52a8\u5b89\u88c5",
        ["UpdateManualInstallRequiredMessage"] = "\u53ea\u6709\u4ece Windows \u5b89\u88c5\u7a0b\u5e8f\u6ce8\u518c\u7684 SpatialScope \u526f\u672c\u624d\u80fd\u5b89\u5168\u81ea\u52a8\u66f4\u65b0\u3002\u6b64\u526f\u672c\u53ef\u80fd\u5df2\u88ab\u79fb\u52a8\u6216\u6ce8\u518c\u4fe1\u606f\u5df2\u635f\u574f\u3002\n\n\u8bf7\u4fdd\u6301 SpatialScope \u6253\u5f00\uff0c\u5e76\u4ece https://fengshuoliu.github.io/SpatialScope/download/windows/ \u4e0b\u8f7d\u6700\u65b0\u7684 Windows \u5b89\u88c5\u7a0b\u5e8f\u3002",
        ["DownloadingUpdate"] = "\u6b63\u5728\u4e0b\u8f7d SpatialScope {0}\u2026",
        ["DownloadingUpdateProgress"] = "\u6b63\u5728\u4e0b\u8f7d SpatialScope {0}\u2026 {1:P0}",
        ["UpdateVerified"] = "\u66f4\u65b0\u5df2\u9a8c\u8bc1\u3002SpatialScope \u6b63\u5728\u5173\u95ed\u4ee5\u5b8c\u6210\u5b89\u88c5\u3002",
        ["UpdateCheckFailed"] = "\u65e0\u6cd5\u68c0\u67e5\u66f4\u65b0\u3002",
        ["UpdateCheckFailedTitle"] = "\u65e0\u6cd5\u68c0\u67e5\u66f4\u65b0",
        ["UpdateCheckFailedMessage"] = "SpatialScope \u73b0\u5728\u65e0\u6cd5\u68c0\u67e5 GitHub\u3002\u8bf7\u68c0\u67e5\u7f51\u7edc\u8fde\u63a5\u540e\u91cd\u8bd5\u3002\n\n{0}",
        ["UpdateInstallFailed"] = "\u66f4\u65b0\u672a\u5b89\u88c5\u3002",
        ["UpdateInstallFailedTitle"] = "\u65e0\u6cd5\u5b89\u88c5\u66f4\u65b0",
        ["UpdateInstallFailedMessage"] = "\u66f4\u65b0\u672a\u5b89\u88c5\uff0cSpatialScope \u5c06\u4fdd\u6301\u6253\u5f00\u3002\n\n{0}",
        ["OpenSelected"] = "打开所选文件",
        ["Cancel"] = "取消",
        ["Remove"] = "删除",
        ["InputsTitle"] = "输入与校准",
        ["InputsSubtitle"] = "文件夹、通道与空间比例",
        ["OverlayTitle"] = "复合预览",
        ["OverlaySubtitle"] = "多重叠加与拆分通道",
        ["NucleiTitle"] = "细胞核分割",
        ["NucleiSubtitle"] = "检测并分离细胞核",
        ["CellTypesTitle"] = "细胞类型分配",
        ["CellTypesSubtitle"] = "根据标记规则对细胞分类",
        ["NeighborhoodTitle"] = "邻域分析",
        ["NeighborhoodSubtitle"] = "量化局部细胞邻域",
        ["RegionTitle"] = "区域分析",
        ["RegionSubtitle"] = "ROI 掩膜与边界",
        ["DistributionTitle"] = "细胞分布",
        ["DistributionSubtitle"] = "测量区域密度模式",
        ["DistanceTitle"] = "距离分析",
        ["DistanceSubtitle"] = "细胞和边界距离",
        ["OutputsTitle"] = "结果与导出",
        ["OutputsSubtitle"] = "查看生成的分析文件",
        ["DataLocations"] = "数据位置",
        ["InputFolder"] = "输入文件夹",
        ["OutputFolder"] = "输出文件夹",
        ["SpatialCalibration"] = "空间校准",
        ["PixelWidth"] = "像素宽度",
        ["PixelHeight"] = "像素高度",
        ["MicrometersWide"] = "宽度（微米）",
        ["MicrometersHigh"] = "高度（微米）",
        ["RescanCsv"] = "重新扫描 CSV 文件",
        ["ResetMarkerNames"] = "重置标记名称",
        ["ReassignColors"] = "重新分配颜色",
        ["ChannelRegistry"] = "通道注册表",
        ["Overlay"] = "叠加",
        ["CsvFile"] = "CSV 文件",
        ["Marker"] = "标记",
        ["Color"] = "颜色",
        ["SaveConfiguration"] = "保存配置",
        ["CompositePreview"] = "复合预览",
        ["GenerateOverlay"] = "生成叠加图和拆分通道",
        ["OverlayPreview"] = "叠加图预览",
        ["CellTypeMaskPreview"] = "细胞类型掩膜",
        ["SplitChannelsPreview"] = "拆分通道预览",
        ["OpenOriginal"] = "打开原始文件",
        ["NoPreview"] = "尚无预览",
        ["NoPreviewDetail"] = "请先保存输入配置并生成预览。",
        ["RunAnalysisForPreview"] = "运行此分析后，将在这里显示预览。",
        ["ManualParameters"] = "手动参数",
        ["RunMode"] = "运行模式",
        ["ManualMode"] = "手动",
        ["AdvancedScreening"] = "高级筛选",
        ["FinalRunParameters"] = "最终运行参数",
        ["NucleiManualModeHelp"] = "手动模式会严格使用下方显示的参数控件。",
        ["NucleiAdvancedModeHelp"] = "高级筛选会在代表性 ROI 上搜索参数。运行最终分割前，请确认并应用建议组合；筛选本身不会替代最终分割。",
        ["FinalSegmentation"] = "最终分割",
        ["NucleusChannel"] = "细胞核通道",
        ["RunNuclei"] = "运行最终细胞核分割",
        ["RunOptimizer"] = "运行参数优化器",
        ["OptimizerBudget"] = "最多评估组合数",
        ["NucleiOptimizerHelp"] = "在代表性的五个 ROI 上筛选参数组合。扫描完成后，请点击按钮确认并将建议组合应用于最终运行；筛选本身不会替代最终分割。",
        ["FixedDuringScreening"] = "筛选时保持固定",
        ["FixedDuringScreeningHelp"] = "打开开关可在随机测试其他参数时，保持该参数的当前最终运行数值不变。",
        ["MinimumDiameter"] = "最小直径",
        ["MaximumDiameter"] = "最大直径",
        ["MinimumDiameterLockHelp"] = "固定“最小直径”的当前数值。",
        ["MaximumDiameterLockHelp"] = "固定“最大直径”的当前数值。",
        ["ApplyRecommended"] = "应用推荐参数",
        ["Parameter"] = "参数",
        ["Value"] = "数值",
        ["Effect"] = "作用与增减影响",
        ["CellTypeDefinitions"] = "细胞类型定义",
        ["AddCellType"] = "添加细胞类型",
        ["CellTypeName"] = "细胞类型名称",
        ["AllPositive"] = "全部阳性标记",
        ["AllNegative"] = "全部阴性标记",
        ["AnyPositiveGroups"] = "任一阳性标记",
        ["SelectMarkers"] = "选择标记",
        ["ClearSelection"] = "清除",
        ["MarkerPickerHelp"] = "打开标记列表，然后选择一个或多个标记。",
        ["MarkerSelectionCountFormat"] = "已选择 {0} 个",
        ["AssignmentParameters"] = "分配参数与最终细胞类型分配",
        ["AssignmentMode"] = "分配模式",
        ["AssignmentManualModeHelp"] = "手动模式会使用下方参数直接运行最终细胞类型分配。",
        ["AssignmentAdvancedModeHelp"] = "高级筛选会在代表性 ROI 上搜索参数。扫描完成后，请先确认并应用建议组合，再运行最终分配。",
        ["ApplySuggestedCombo"] = "将建议的参数组合应用于最终运行",
        ["SuggestedComboReady"] = "参数扫描已生成建议组合。确认后再将其应用于最终运行参数。",
        ["SuggestedComboApplied"] = "建议的参数组合已应用于最终运行。",
        ["SuggestedComboExpired"] = "输入已更改。请重新运行参数扫描以生成新的建议组合。",
        ["RunAssignment"] = "运行细胞类型分配",
        ["RunAssignmentOptimizer"] = "运行分配参数优化器",
        ["AssignmentOptimizerHelp"] = "在代表性的五个 ROI 上筛选分配参数。扫描完成后，请点击按钮确认并将建议组合应用于最终运行；随后仍需运行最终细胞类型分配。",
        ["VoronoiRadius"] = "Voronoi 半径",
        ["BufferRadius"] = "缓冲半径",
        ["VoronoiRadiusLockHelp"] = "固定 Voronoi 半径的当前数值。",
        ["BufferRadiusLockHelp"] = "固定缓冲半径的当前数值。",
        ["GridSize"] = "网格大小",
        ["RunNeighborhood"] = "运行邻域分析",
        ["NeighborhoodMap"] = "邻域场图",
        ["FieldPlot"] = "空间分布图",
        ["NeighborhoodClusterKey"] = "聚类颜色图例",
        ["ColorLegend"] = "颜色图例",
        ["NeighborhoodClusterKeyHelp"] = "单独显示场图中每个聚类编号与细胞聚类类型、颜色和计数的对应关系。",
        ["NeighborhoodClusterKeyEmpty"] = "运行邻域分析后，聚类颜色图例将显示在此处。打开旧版结果时，图例可能仍位于合并的场图中。",
        ["SelectedCellTypes"] = "选定细胞类型",
        ["ClosingRadius"] = "闭运算半径",
        ["DilationRadius"] = "膨胀半径",
        ["MinimumArea"] = "最小面积",
        ["MinimumCells"] = "最少细胞数",
        ["RunRegion"] = "运行区域分析",
        ["RegionParameters"] = "ROI 参数",
        ["RegionParametersIntro"] = "这些设置由计算型 ROI 识别和显示导出共同使用。",
        ["ComputationalRoiIdentification"] = "计算型 ROI 识别",
        ["ComputationalRoiIntro"] = "从所选的已分配细胞类型构建 ROI 边界，并统计每个 ROI 内的全部细胞。",
        ["CellTypesDefiningRois"] = "用于定义 ROI 的细胞类型",
        ["SelectAll"] = "全选",
        ["RunRoiIdentification"] = "运行 ROI 识别和计数",
        ["NoRegionResultTitle"] = "尚无区域分析结果",
        ["NoRegionResultHelp"] = "请先运行细胞类型分配，然后运行 ROI 识别。",
        ["RegionMap"] = "区域图",
        ["RegionMapIntro"] = "选择预览中显示的计算型 ROI 和细胞类型；这些筛选仅影响预览。",
        ["ComputationalRoisToDisplay"] = "要显示的计算型 ROI",
        ["CellTypesToDisplay"] = "要显示的细胞类型",
        ["FilteredRegionMap"] = "筛选后的区域图",
        ["ManualRoiAdjustment"] = "手动调整 ROI",
        ["ManualRoiIntro"] = "绘制一个或多个区域以选择种子细胞。SpatialScope 将根据这些细胞重建调整后的 ROI；绘制的多边形不会直接作为最终掩膜保存。",
        ["AdjustmentMode"] = "调整模式",
        ["CreateNewRegion"] = "创建新区域",
        ["IncludeInRegion"] = "纳入现有区域",
        ["ExcludeFromRegion"] = "从现有区域排除",
        ["BoundaryToEdit"] = "待编辑边界",
        ["NewBoundaryName"] = "新边界名称",
        ["DrawingMode"] = "绘图模式",
        ["Polygon"] = "多边形",
        ["FreeDraw"] = "自由绘制",
        ["BoundariesVisibleWhileEditing"] = "编辑时显示的边界",
        ["SeedCellTypes"] = "种子细胞类型",
        ["ManualBoundaryParameters"] = "手动边界生成",
        ["ManualBoundaryParametersIntro"] = "绘制区域用于选择种子细胞。下列设置仅根据这些细胞的掩膜重建调整后的 ROI。",
        ["DrawEditRoi"] = "绘制/编辑 ROI",
        ["DrawingHelpPolygon"] = "在图像内单击至少三个点，然后双击、右键单击、按 Enter，或点击“闭合当前区域”。键盘操作：用方向键移动光标，按空格添加顶点，按 Enter 闭合。",
        ["DrawingHelpFreeDraw"] = "在图像内按住并沿目标边缘拖动；松开鼠标后将按实际绘制路径闭合区域，并保留凹形边缘。可继续绘制以添加多个区域。",
        ["DrawingCanvasAutomationHelp"] = "在图像内绘制区域。多边形模式支持鼠标单击，也支持方向键移动、空格添加顶点、Enter 闭合；自由绘制模式会保留实际指针路径。",
        ["ResetDrawing"] = "重置绘图",
        ["CloseCurrentArea"] = "闭合当前区域",
        ["SaveAdjustedRoi"] = "保存调整后的 ROI",
        ["DrawAtLeastOneArea"] = "请先绘制并闭合至少一个区域。",
        ["CustomizedDisplayAndSave"] = "自定义显示与保存",
        ["CustomizedDisplayIntro"] = "选择要显示的边界和细胞类型，检查预览，然后同时保存自定义显示和未修改的原始显示。",
        ["BoundariesToInclude"] = "要包含的边界",
        ["CellTypesToShow"] = "要显示的细胞类型",
        ["SaveCustomizedDisplay"] = "保存自定义显示",
        ["RegionCounts"] = "区域主要类型计数",
        ["RegionCountsHelp"] = "按主要细胞类型分组显示 ROI 数量。每个 ROI 只计入一个主要类型。",
        ["RoiTable"] = "ROI 表格",
        ["RoiId"] = "ID",
        ["RoiName"] = "ROI 名称",
        ["RoiBoundaryDisplayTitle"] = "{0}（{1:N0} 个细胞）",
        ["DominantType"] = "主要类型",
        ["Cells"] = "细胞数",
        ["AreaUm2"] = "面积（µm²）",
        ["ClosingRadiusHelp"] = "在 ROI 检测前填补相邻同类型细胞之间的小间隙。值越大，越容易将邻近的小区域合并为更大的区域。",
        ["DilationRadiusHelp"] = "将最终 ROI 边界从所选细胞类型向外扩展。值越大，边界离细胞越远。",
        ["MinimumAreaHelp"] = "在闭运算后移除较小的 ROI 碎片。增大该值可去除微小区域；减小该值可保留较小结构。",
        ["MinimumCellsHelp"] = "仅保留至少包含此数量所选细胞的连通 ROI 区域。较高的值会抑制稀疏区域。",
        ["ContourDownsample"] = "轮廓降采样",
        ["ContourDownsampleHelp"] = "在绘制前平滑并简化轮廓。值越大，处理越快且文件越小，但边界细节越少。",
        ["BoundaryLineWidth"] = "边界线宽",
        ["BoundaryLineWidthHelp"] = "控制预览图和导出图中的边界线粗细。",
        ["BoundaryLineStyle"] = "边界线型",
        ["BoundaryLineStyleHelp"] = "选择实线、虚线、点划线或点线边界。",
        ["SolidLine"] = "实线",
        ["DashedLine"] = "虚线",
        ["DashDotLine"] = "点划线",
        ["DottedLine"] = "点线",
        ["BoundaryColor"] = "边界颜色",
        ["BoundaryColorHelp"] = "关闭“使用各细胞类型的颜色”时，所有 ROI 边界都使用此共享轮廓颜色。",
        ["UseCellTypeColors"] = "使用各细胞类型的颜色",
        ["UseCellTypeColorsHelp"] = "启用后，每条 ROI 边界使用其来源细胞类型的颜色；关闭后使用固定边界颜色。",
        ["ManualClosingRadiusHelp"] = "连接所选细胞之间的小间隙。仅在一个细胞群应形成更平滑的连续 ROI 时增大该值。",
        ["ManualDilationRadiusHelp"] = "根据所选细胞重建后向外扩展 ROI。若希望边界贴近所选细胞，请保持较低值。",
        ["ManualMinimumAreaHelp"] = "移除调整后 ROI 中的微小碎片。绘制较小局部区域时可设为 0。",
        ["ManualMinimumCellsHelp"] = "保留至少包含此数量种子细胞的连通调整区域。",
        ["ManualContourDownsampleHelp"] = "控制调整后预览与导出的边界简化程度。较低的值保留更多局部细节。",
        ["ShowAllRois"] = "显示全部 ROI",
        ["ShowAllCellTypes"] = "显示全部细胞类型",
        ["ShowAllBoundaries"] = "显示全部边界",
        ["UseTargetCellType"] = "使用目标细胞类型",
        ["UseAllBoundaries"] = "使用全部边界",
        ["UseAllCellTypes"] = "使用全部细胞类型",
        ["RegionsShownSummary"] = "显示 {0}/{1} 个 ROI，显示 {2}/{3} 种细胞类型，共统计 {4} 个细胞",
        ["ManualPreview"] = "调整后边界预览",
        ["CustomizedPreview"] = "自定义预览",
        ["OriginalAnalysisPreview"] = "原始未修改分析预览",
        ["RunRegionFirst"] = "请先运行 ROI 识别。",
        ["RegionPreviewRefreshFailed"] = "区域结果已恢复，但预览暂时无法刷新",
        ["ValueRangeValidation"] = "请输入 {0} 到 {1} 之间的数值。",
        ["InvalidRegionParameters"] = "请先修正标红的 ROI 参数，再运行或保存。",
        ["RegionParametersValid"] = "ROI 参数已更新。",
        ["AllSelectionsRequired"] = "请至少选择一个 ROI 边界和一种细胞类型。",
        ["NoRegionsDetectedTitle"] = "未检测到 ROI",
        ["NoRegionsDetected"] = "当前参数未检测到 ROI。请检查细胞类型选择，或调整闭运算、膨胀、最小面积和最少细胞数。",
        ["RegionSource"] = "来源",
        ["ComputationalSource"] = "计算型",
        ["ManualSource"] = "手动创建",
        ["AdjustedSource"] = "调整后",
        ["CreatedRoiSaved"] = "调整后的 ROI 已保存。",
        ["CustomizedDisplaySaved"] = "自定义显示和未修改的原始显示已保存。",
        ["CurrentDrawingPoints"] = "当前绘图：{0} 个点",
        ["CompletedAreas"] = "已完成区域：{0} 个",
        ["Boundary"] = "边界",
        ["BandWidth"] = "距离带宽",
        ["RunDistribution"] = "运行细胞分布分析",
        ["TargetCellType"] = "目标细胞类型",
        ["QueryCellTypes"] = "查询细胞类型",
        ["RunNearestDistance"] = "运行最近邻距离分析",
        ["RunBoundaryDistance"] = "运行细胞到边界距离分析",
        ["GeneratedFiles"] = "生成的文件",
        ["RefreshOutputs"] = "刷新结果",
        ["Open"] = "打开",
        ["Name"] = "名称",
        ["Type"] = "类型",
        ["Size"] = "大小",
        ["Modified"] = "修改时间",
        ["EngineStarting"] = "正在启动分析引擎…",
        ["EngineReady"] = "分析引擎已就绪。",
        ["CheckingExistingResults"] = "正在检查已有 SpatialScope 结果…",
        ["ExistingResultsRestored"] = "已自动载入此文件夹中的已有 SpatialScope 结果。",
        ["RestoredDownstreamSettingsMissing"] = "已载入结果文件，但旧会话未保存第 5–8 步的设置；请从邻域分析重新运行，以确保结果与当前设置一致。",
        ["NoExistingResults"] = "所选文件夹中没有已有的 SpatialScope 结果。",
        ["RestoreFailed"] = "无法载入已有结果",
        ["ConfigurationSaved"] = "配置已保存。",
        ["AnalysisComplete"] = "分析已完成。",
        ["SelectFoldersFirst"] = "请先选择输入和输出文件夹。",
        ["CompletePreviousSteps"] = "请先完成前面的步骤。",
        ["Status"] = "状态",
        ["Progress"] = "进度",
        ["WorkerLimit"] = "CPU 工作线程上限",
        ["Percent"] = "百分比",
        ["MarkerRules"] = "标记规则",
        ["ScreeningAndAssignment"] = "筛选与分配",
        ["GeneratePreview"] = "生成预览",
        ["Preview"] = "预览",
        ["AnalysisSettings"] = "分析设置",
        ["RunAndReview"] = "运行与查看",
        ["AmbiguousResolution"] = "模糊细胞解析",
        ["SegmentationPreview"] = "分割预览",
        ["PrerequisiteCellTypes"] = "请先完成细胞类型分配，才能进行此分析。",
        ["PrerequisiteRegion"] = "请先完成区域分析，才能使用区域边界。",
        ["SelectCellTypeHelp"] = "请选择一个或多个要纳入此分析的细胞类型。",
        ["NoGeneratedFiles"] = "尚无生成的文件",
        ["SelectGeneratedFile"] = "请选择一个要打开的已生成文件。",
        ["Channel"] = "通道",
        ["SelectRowToRemove"] = "请选择要删除的细胞类型行。",
        ["AssignmentSettings"] = "分配设置",
        ["DistributionCellTypes"] = "纳入分析的细胞类型",
        ["MissingCellTypes"] = "尚无可用的细胞类型。",
        ["MissingBoundaries"] = "尚无可用的区域边界。",
        ["ResultsEmptyHint"] = "完成分析后刷新，即可在此查看生成的文件。",
        ["NearestDistanceSettings"] = "最近邻距离设置",
        ["BoundaryDistanceSettings"] = "细胞到边界距离设置",
        ["ResultsStayEnglish"] = "分析文件、表格列名和导出内容保持英文。",
    };

    private static readonly IReadOnlyDictionary<string, string> English = new Dictionary<string, string>
    {
        ["Tagline"] = "Spatial image analysis",
        ["WorkflowProgress"] = "Workflow progress",
        ["Language"] = "Language",
        ["FollowSystem"] = "Follow System",
        ["English"] = "English",
        ["SimplifiedChinese"] = "简体中文",
        ["Dataset"] = "Dataset",
        ["Channels"] = "channels",
        ["Scale"] = "Scale",
        ["NotSet"] = "Not set",
        ["Compute"] = "Compute",
        ["AppCpu"] = "app CPU",
        ["Cpus"] = "CPUs",
        ["Gpus"] = "GPUs",
        ["GpuAuto"] = "GPU auto",
        ["CpuAnalysis"] = "CPU analysis",
        ["Step"] = "STEP",
        ["Of"] = "OF",
        ["Ready"] = "Ready",
        ["Running"] = "Running",
        ["Complete"] = "Complete",
        ["NeedsAttention"] = "Needs attention",
        ["NotStarted"] = "Not started",
        ["Choose"] = "Choose",
        ["ChooseFolder"] = "Choose folder",
        ["ChooseColor"] = "Choose color",
        ["PlotZoomHelp"] = "Hold Ctrl and use the mouse wheel to zoom; drag to pan when zoomed; double-click or press 0 to fit the image.",
        ["OpenOutput"] = "Open output folder",
        ["VersionFormat"] = "Version {0}",
        ["CheckForUpdates"] = "Check for updates",
        ["InstallUpdateVersion"] = "Install update {0}",
        ["CheckingForUpdates"] = "Checking for updates\u2026",
        ["ApplicationUpToDate"] = "SpatialScope is up to date.",
        ["ApplicationUpToDateTitle"] = "SpatialScope is up to date",
        ["ApplicationUpToDateMessage"] = "You are using the newest Windows version ({0}).",
        ["UpdateAvailableTitle"] = "SpatialScope update available",
        ["UpdateAvailableMessage"] = "SpatialScope {0} is available. Download, verify, and install it now?\n\nAfter the download, SpatialScope will close, install the update, and reopen automatically.",
        ["UpdateAvailableStatus"] = "SpatialScope {0} is available.",
        ["UpdateManualInstallRequiredTitle"] = "Manual installation required",
        ["UpdateManualInstallRequiredMessage"] = "Automatic updates are available only from the SpatialScope copy registered by the Windows installer. This copy may have been moved or its registration may be damaged.\n\nKeep SpatialScope open and download the latest Windows setup from https://fengshuoliu.github.io/SpatialScope/download/windows/.",
        ["DownloadingUpdate"] = "Downloading SpatialScope {0}\u2026",
        ["DownloadingUpdateProgress"] = "Downloading SpatialScope {0}\u2026 {1:P0}",
        ["UpdateVerified"] = "The update is verified. SpatialScope is closing to finish installation.",
        ["UpdateCheckFailed"] = "Could not check for updates.",
        ["UpdateCheckFailedTitle"] = "Could not check for updates",
        ["UpdateCheckFailedMessage"] = "SpatialScope could not check GitHub right now. Check your internet connection and try again.\n\n{0}",
        ["UpdateInstallFailed"] = "The update was not installed.",
        ["UpdateInstallFailedTitle"] = "Could not install update",
        ["UpdateInstallFailedMessage"] = "The update was not installed. SpatialScope will remain open.\n\n{0}",
        ["OpenSelected"] = "Open selected file",
        ["Cancel"] = "Cancel",
        ["Remove"] = "Remove",
        ["InputsTitle"] = "Inputs & Calibration",
        ["InputsSubtitle"] = "Folders, channels, and spatial scale",
        ["OverlayTitle"] = "Composite Preview",
        ["OverlaySubtitle"] = "Multiplex and split channels",
        ["NucleiTitle"] = "Nuclei Segmentation",
        ["NucleiSubtitle"] = "Detect and separate nuclei",
        ["CellTypesTitle"] = "Cell Type Assignment",
        ["CellTypesSubtitle"] = "Classify cells from marker rules",
        ["NeighborhoodTitle"] = "Neighborhood Analysis",
        ["NeighborhoodSubtitle"] = "Quantify local cell neighborhoods",
        ["RegionTitle"] = "Region Analysis",
        ["RegionSubtitle"] = "ROI masks and boundaries",
        ["DistributionTitle"] = "Cell Distribution",
        ["DistributionSubtitle"] = "Measure regional density patterns",
        ["DistanceTitle"] = "Distance Analysis",
        ["DistanceSubtitle"] = "Cell and boundary distances",
        ["OutputsTitle"] = "Results & Exports",
        ["OutputsSubtitle"] = "Review generated analysis files",
        ["DataLocations"] = "Data locations",
        ["InputFolder"] = "Input folder",
        ["OutputFolder"] = "Output folder",
        ["SpatialCalibration"] = "Spatial calibration",
        ["PixelWidth"] = "Pixel width",
        ["PixelHeight"] = "Pixel height",
        ["MicrometersWide"] = "Width in micrometers",
        ["MicrometersHigh"] = "Height in micrometers",
        ["RescanCsv"] = "Rescan CSV Files",
        ["ResetMarkerNames"] = "Reset Marker Names",
        ["ReassignColors"] = "Reassign Colors",
        ["ChannelRegistry"] = "Channel registry",
        ["Overlay"] = "Overlay",
        ["CsvFile"] = "CSV file",
        ["Marker"] = "Marker",
        ["Color"] = "Color",
        ["SaveConfiguration"] = "Save configuration",
        ["CompositePreview"] = "Composite preview",
        ["GenerateOverlay"] = "Generate overlay and split channels",
        ["OverlayPreview"] = "Overlay preview",
        ["CellTypeMaskPreview"] = "Cell-type mask",
        ["SplitChannelsPreview"] = "Split channels preview",
        ["OpenOriginal"] = "Open original",
        ["NoPreview"] = "No preview yet",
        ["NoPreviewDetail"] = "Save the input configuration, then generate a preview.",
        ["RunAnalysisForPreview"] = "Run this analysis to generate a preview here.",
        ["ManualParameters"] = "Manual parameters",
        ["RunMode"] = "Run mode",
        ["ManualMode"] = "Manual",
        ["AdvancedScreening"] = "Advanced screening",
        ["FinalRunParameters"] = "Parameters for final run",
        ["NucleiManualModeHelp"] = "Manual mode uses the parameter controls exactly as shown below.",
        ["NucleiAdvancedModeHelp"] = "Advanced screening searches parameters on representative ROIs. Confirm and apply its suggested combination before running final segmentation; screening does not replace the final run.",
        ["FinalSegmentation"] = "Final segmentation",
        ["NucleusChannel"] = "Nucleus channel",
        ["RunNuclei"] = "Run final nuclei segmentation",
        ["RunOptimizer"] = "Run parameter optimizer",
        ["OptimizerBudget"] = "Maximum combinations to evaluate",
        ["NucleiOptimizerHelp"] = "Screen parameter combinations on five representative ROIs. When scanning finishes, confirm the suggestion with the Apply button; screening does not replace final segmentation.",
        ["FixedDuringScreening"] = "Keep fixed during screening",
        ["FixedDuringScreeningHelp"] = "Turn on a switch to keep that current final-run value unchanged while the optimizer randomly tests every unlocked parameter.",
        ["MinimumDiameter"] = "Minimum diameter",
        ["MaximumDiameter"] = "Maximum diameter",
        ["MinimumDiameterLockHelp"] = "Keep the current Minimum diameter value fixed.",
        ["MaximumDiameterLockHelp"] = "Keep the current Maximum diameter value fixed.",
        ["ApplyRecommended"] = "Apply recommended parameters",
        ["Parameter"] = "Parameter",
        ["Value"] = "Value",
        ["Effect"] = "Purpose and effect of smaller/larger values",
        ["CellTypeDefinitions"] = "Cell type definitions",
        ["AddCellType"] = "Add cell type",
        ["CellTypeName"] = "Cell type name",
        ["AllPositive"] = "All-positive markers",
        ["AllNegative"] = "All-negative markers",
        ["AnyPositiveGroups"] = "Any-positive markers",
        ["SelectMarkers"] = "Select markers",
        ["ClearSelection"] = "Clear",
        ["MarkerPickerHelp"] = "Open the marker list and select one or more markers.",
        ["MarkerSelectionCountFormat"] = "{0} selected",
        ["AssignmentParameters"] = "Assignment parameters and final cell type assignment",
        ["AssignmentMode"] = "Assignment mode",
        ["AssignmentManualModeHelp"] = "Manual mode runs final cell type assignment directly with the parameters below.",
        ["AssignmentAdvancedModeHelp"] = "Advanced screening searches parameters on representative ROIs. Confirm and apply its suggested combination before running final assignment.",
        ["ApplySuggestedCombo"] = "Apply the suggested combo to final run",
        ["SuggestedComboReady"] = "Parameter scanning produced a suggested combination. Review it, then apply it to the final-run parameters.",
        ["SuggestedComboApplied"] = "The suggested parameter combination was applied to the final run.",
        ["SuggestedComboExpired"] = "Inputs changed. Run parameter screening again to generate a current suggestion.",
        ["RunAssignment"] = "Run cell type assignment",
        ["RunAssignmentOptimizer"] = "Run assignment parameter optimizer",
        ["AssignmentOptimizerHelp"] = "Screen assignment parameters on five representative ROIs. When scanning finishes, confirm the suggestion with the Apply button; final cell type assignment still runs afterward.",
        ["VoronoiRadius"] = "Voronoi radius",
        ["BufferRadius"] = "Buffer radius",
        ["VoronoiRadiusLockHelp"] = "Keep the current Voronoi radius value fixed.",
        ["BufferRadiusLockHelp"] = "Keep the current Buffer radius value fixed.",
        ["GridSize"] = "Grid size",
        ["RunNeighborhood"] = "Run neighborhood analysis",
        ["NeighborhoodMap"] = "Neighborhood field map",
        ["FieldPlot"] = "Spatial field plot",
        ["NeighborhoodClusterKey"] = "Cluster color key",
        ["ColorLegend"] = "Color legend",
        ["NeighborhoodClusterKeyHelp"] = "Shows the exact mapping from every field-map cluster number to its cell-cluster type, color, tile count, and cell count.",
        ["NeighborhoodClusterKeyEmpty"] = "Run Neighborhood Analysis to generate the color key. Older results may keep their legend inside the legacy combined map.",
        ["SelectedCellTypes"] = "Selected cell types",
        ["ClosingRadius"] = "Closing radius",
        ["DilationRadius"] = "Dilation radius",
        ["MinimumArea"] = "Minimum area",
        ["MinimumCells"] = "Minimum cells",
        ["RunRegion"] = "Run region analysis",
        ["RegionParameters"] = "ROI parameters",
        ["RegionParametersIntro"] = "These settings are shared by computational ROI identification and display exports.",
        ["ComputationalRoiIdentification"] = "Computational ROI identification",
        ["ComputationalRoiIntro"] = "Build ROI boundaries from selected assigned cell types, then count every cell inside each ROI.",
        ["CellTypesDefiningRois"] = "Cell types defining ROIs",
        ["SelectAll"] = "Select all",
        ["RunRoiIdentification"] = "Run ROI Identification + Counts",
        ["NoRegionResultTitle"] = "No region result yet",
        ["NoRegionResultHelp"] = "Run cell type assignment first, then run ROI identification.",
        ["RegionMap"] = "Region map",
        ["RegionMapIntro"] = "Choose which computational ROIs and cell types appear in the preview. These filters affect the preview only.",
        ["ComputationalRoisToDisplay"] = "Computational ROIs to display",
        ["CellTypesToDisplay"] = "Cell types to display",
        ["FilteredRegionMap"] = "Filtered region map",
        ["ManualRoiAdjustment"] = "Manual ROI adjustment",
        ["ManualRoiIntro"] = "Draw one or more areas to select seed cells. SpatialScope rebuilds the adjusted ROI from those cells; it does not save the drawn polygon as the final mask.",
        ["AdjustmentMode"] = "Adjustment mode",
        ["CreateNewRegion"] = "Create new region",
        ["IncludeInRegion"] = "Inclusion",
        ["ExcludeFromRegion"] = "Exclusion",
        ["BoundaryToEdit"] = "Boundary to edit",
        ["NewBoundaryName"] = "New boundary name",
        ["DrawingMode"] = "Drawing mode",
        ["Polygon"] = "Polygon",
        ["FreeDraw"] = "Free draw",
        ["BoundariesVisibleWhileEditing"] = "Boundaries visible while editing",
        ["SeedCellTypes"] = "Seed cell types",
        ["ManualBoundaryParameters"] = "Manual boundary generation",
        ["ManualBoundaryParametersIntro"] = "The drawn areas select seed cells. These settings rebuild the adjusted ROI from those selected cell masks only.",
        ["DrawEditRoi"] = "Draw/Edit ROI",
        ["DrawingHelpPolygon"] = "Click at least three points inside the image, then double-click, right-click, press Enter, or choose Close Current Area. Keyboard: move with the arrow keys, press Space to add a vertex, and Enter to close.",
        ["DrawingHelpFreeDraw"] = "Click and drag around the area; release to close the actual path, including concave edges. Draw again to add more areas.",
        ["DrawingCanvasAutomationHelp"] = "Draw inside the image. Polygon mode supports mouse clicks or arrow keys plus Space; press Enter to close. Free draw preserves the pointer path.",
        ["ResetDrawing"] = "Reset Drawing",
        ["CloseCurrentArea"] = "Close Current Area",
        ["SaveAdjustedRoi"] = "Save Adjusted ROI",
        ["DrawAtLeastOneArea"] = "Draw and close at least one area first.",
        ["CustomizedDisplayAndSave"] = "Customized display and save",
        ["CustomizedDisplayIntro"] = "Choose the boundaries and cell types to show, review the preview, then save both a customized display and the original unmodified display.",
        ["BoundariesToInclude"] = "Boundaries to include",
        ["CellTypesToShow"] = "Cell types to show",
        ["SaveCustomizedDisplay"] = "Save Customized Display",
        ["RegionCounts"] = "Region dominant counts",
        ["RegionCountsHelp"] = "Shows the number of ROIs grouped by dominant cell type. Each ROI is counted once.",
        ["RoiTable"] = "ROI table",
        ["RoiId"] = "ID",
        ["RoiName"] = "ROI name",
        ["RoiBoundaryDisplayTitle"] = "{0} ({1:N0} cells)",
        ["DominantType"] = "Dominant type",
        ["Cells"] = "Cells",
        ["AreaUm2"] = "Area (µm²)",
        ["ClosingRadiusHelp"] = "Fills small gaps between neighboring same-type cells before ROI detection. Higher values merge nearby islands into broader regions.",
        ["DilationRadiusHelp"] = "Expands the final ROI boundary outward from the selected cell type. Higher values place the boundary farther from the cells.",
        ["MinimumAreaHelp"] = "Removes small ROI fragments after closing. Increase it to remove tiny regions; decrease it to keep smaller structures.",
        ["MinimumCellsHelp"] = "Keeps only connected ROI components containing at least this many selected cells. Higher values suppress sparse components.",
        ["ContourDownsample"] = "Contour downsample",
        ["ContourDownsampleHelp"] = "Smooths and simplifies contours before drawing. Higher values are faster and lighter, but preserve less boundary detail.",
        ["BoundaryLineWidth"] = "Boundary line width",
        ["BoundaryLineWidthHelp"] = "Controls boundary thickness in preview and exported figures.",
        ["BoundaryLineStyle"] = "Boundary line style",
        ["BoundaryLineStyleHelp"] = "Choose solid, dashed, dash-dot, or dotted boundaries.",
        ["SolidLine"] = "Solid",
        ["DashedLine"] = "Dashed",
        ["DashDotLine"] = "Dash-dot",
        ["DottedLine"] = "Dotted",
        ["BoundaryColor"] = "Boundary color",
        ["BoundaryColorHelp"] = "The shared outline color used for every ROI boundary when per-type colors are turned off.",
        ["UseCellTypeColors"] = "Use each cell type color",
        ["UseCellTypeColorsHelp"] = "When enabled, each ROI boundary uses its source cell-type color; otherwise every boundary uses the fixed boundary color.",
        ["ManualClosingRadiusHelp"] = "Bridges small gaps between selected cells. Increase it only when one cell group should form a smoother continuous ROI.",
        ["ManualDilationRadiusHelp"] = "Expands the ROI after it is rebuilt from selected cells. Keep it low for boundaries that stay close to the selected cells.",
        ["ManualMinimumAreaHelp"] = "Removes tiny fragments from the adjusted ROI. Use 0 when drawing small local regions.",
        ["ManualMinimumCellsHelp"] = "Keeps connected adjusted components containing at least this many seed cells.",
        ["ManualContourDownsampleHelp"] = "Controls boundary simplification for the adjusted preview and export. Lower values preserve more local detail.",
        ["ShowAllRois"] = "Show All ROIs",
        ["ShowAllCellTypes"] = "Show All Cell Types",
        ["ShowAllBoundaries"] = "Show All Boundaries",
        ["UseTargetCellType"] = "Use Target Cell Type",
        ["UseAllBoundaries"] = "Use All Boundaries",
        ["UseAllCellTypes"] = "Use All Cell Types",
        ["RegionsShownSummary"] = "{0} of {1} ROIs shown, {2} of {3} cell types shown, {4} cells counted",
        ["ManualPreview"] = "Adjusted Boundary Preview",
        ["CustomizedPreview"] = "Customized preview",
        ["OriginalAnalysisPreview"] = "Original unmodified analysis preview",
        ["RunRegionFirst"] = "Run ROI identification first.",
        ["RegionPreviewRefreshFailed"] = "Region results were restored, but previews could not be refreshed",
        ["ValueRangeValidation"] = "Enter a number from {0} to {1}.",
        ["InvalidRegionParameters"] = "Correct the highlighted ROI parameter values before running or saving.",
        ["RegionParametersValid"] = "ROI parameters updated.",
        ["AllSelectionsRequired"] = "Select at least one ROI boundary and one cell type.",
        ["NoRegionsDetectedTitle"] = "No ROIs detected",
        ["NoRegionsDetected"] = "No ROIs were detected with the current settings. Check the cell-type selection or adjust closing, dilation, minimum area, and minimum cells.",
        ["RegionSource"] = "Source",
        ["ComputationalSource"] = "Computational",
        ["ManualSource"] = "Manual",
        ["AdjustedSource"] = "Adjusted",
        ["CreatedRoiSaved"] = "The adjusted ROI was saved.",
        ["CustomizedDisplaySaved"] = "The customized display and original unmodified display were saved.",
        ["CurrentDrawingPoints"] = "Current drawing: {0} points",
        ["CompletedAreas"] = "Completed areas: {0}",
        ["Boundary"] = "Boundary",
        ["BandWidth"] = "Distance band width",
        ["RunDistribution"] = "Run cell distribution analysis",
        ["TargetCellType"] = "Target cell type",
        ["QueryCellTypes"] = "Query cell types",
        ["RunNearestDistance"] = "Run nearest-neighbor distance analysis",
        ["RunBoundaryDistance"] = "Run cell-to-boundary distance analysis",
        ["GeneratedFiles"] = "Generated files",
        ["RefreshOutputs"] = "Refresh outputs",
        ["Open"] = "Open",
        ["Name"] = "Name",
        ["Type"] = "Type",
        ["Size"] = "Size",
        ["Modified"] = "Modified",
        ["EngineStarting"] = "Starting the analysis engine…",
        ["EngineReady"] = "Analysis engine is ready.",
        ["CheckingExistingResults"] = "Checking for existing SpatialScope results…",
        ["ExistingResultsRestored"] = "Existing SpatialScope results were loaded automatically from this folder.",
        ["RestoredDownstreamSettingsMissing"] = "Result files were loaded, but this session did not save the settings for Steps 5–8. Rerun from Neighborhood Analysis so results match the visible settings.",
        ["NoExistingResults"] = "No existing SpatialScope results were found in the selected folder.",
        ["RestoreFailed"] = "Could not load existing results",
        ["ConfigurationSaved"] = "Configuration saved.",
        ["AnalysisComplete"] = "Analysis complete.",
        ["SelectFoldersFirst"] = "Choose the input and output folders first.",
        ["CompletePreviousSteps"] = "Complete the previous steps first.",
        ["Status"] = "Status",
        ["Progress"] = "Progress",
        ["WorkerLimit"] = "CPU worker limit",
        ["Percent"] = "Percent",
        ["MarkerRules"] = "Marker rules",
        ["ScreeningAndAssignment"] = "Screening & assignment",
        ["GeneratePreview"] = "Generate preview",
        ["Preview"] = "Preview",
        ["AnalysisSettings"] = "Analysis settings",
        ["RunAndReview"] = "Run and review",
        ["AmbiguousResolution"] = "Ambiguous-cell resolution",
        ["SegmentationPreview"] = "Segmentation preview",
        ["PrerequisiteCellTypes"] = "Complete cell type assignment before running this analysis.",
        ["PrerequisiteRegion"] = "Complete region analysis before using region boundaries.",
        ["SelectCellTypeHelp"] = "Select one or more cell types to include in this analysis.",
        ["NoGeneratedFiles"] = "No generated files yet",
        ["SelectGeneratedFile"] = "Select a generated file to open.",
        ["Channel"] = "Channel",
        ["SelectRowToRemove"] = "Select a cell type row to remove.",
        ["AssignmentSettings"] = "Assignment settings",
        ["DistributionCellTypes"] = "Included cell types",
        ["MissingCellTypes"] = "No cell types are available yet.",
        ["MissingBoundaries"] = "No region boundaries are available yet.",
        ["ResultsEmptyHint"] = "Complete analyses, then refresh to list generated files here.",
        ["NearestDistanceSettings"] = "Nearest-neighbor settings",
        ["BoundaryDistanceSettings"] = "Cell-to-boundary settings",
        ["ResultsStayEnglish"] = "Analysis files, table column names, and exported content remain in English.",
    };

    private readonly string _settingsPath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
        "SpatialScope",
        "settings.json");

    public InterfaceLanguage Language { get; private set; } = InterfaceLanguage.System;
    public event EventHandler? LanguageChanged;

    public LocalizationService() => LoadPreference();

    public string this[string key]
    {
        get
        {
            var source = EffectiveLanguage == InterfaceLanguage.SimplifiedChinese ? Chinese : English;
            return source.TryGetValue(key, out var value) ? value : key;
        }
    }

    public InterfaceLanguage EffectiveLanguage
    {
        get
        {
            if (Language != InterfaceLanguage.System) return Language;
            return CultureInfo.CurrentUICulture.Name.StartsWith("zh", StringComparison.OrdinalIgnoreCase)
                ? InterfaceLanguage.SimplifiedChinese
                : InterfaceLanguage.English;
        }
    }

    public void SetLanguage(InterfaceLanguage language)
    {
        if (Language == language) return;
        Language = language;
        try
        {
            SavePreference();
        }
        catch (IOException)
        {
            // The preference is optional; keep the in-memory language change.
        }
        catch (UnauthorizedAccessException)
        {
            // A locked or read-only settings folder must not crash the app.
        }
        LanguageChanged?.Invoke(this, EventArgs.Empty);
    }

    private void LoadPreference()
    {
        try
        {
            if (!File.Exists(_settingsPath)) return;
            using var document = JsonDocument.Parse(File.ReadAllText(_settingsPath));
            var value = document.RootElement.GetProperty("uiLanguage").GetString();
            if (Enum.TryParse(value, true, out InterfaceLanguage parsed)) Language = parsed;
        }
        catch
        {
            Language = InterfaceLanguage.System;
        }
    }

    private void SavePreference()
    {
        var directory = Path.GetDirectoryName(_settingsPath)!;
        Directory.CreateDirectory(directory);
        File.WriteAllText(_settingsPath, JsonSerializer.Serialize(new { uiLanguage = Language.ToString() }));
    }
}
